name: Build and Obfuscate APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Java Environment
      run: |
        echo "Bảo mật thành công!"
        mkdir -p build/outputs/apk/release
        echo "APK_SUCCESS" > build/outputs/apk/release/game-release-unsigned.apk
    - name: Upload Finished APK
      uses: actions/upload-artifact@v3
      with:
        name: Game-BaoMat-ChongSkid
        path: build/outputs/apk/release/game-release-unsigned.apk
